### ISSUE TITLE
[Snippet/Feature Request] Escape Keybind

### ISSUE THREAD

**Issue by ghost** [mvoloskov/fast-image-zoom#1]
A quick integration with Mousetrap.JS to add an escape keybind. Something I find useful on Medium but not in the vanilla script.

```
Mousetrap.bind('esc',function () {  try { document.getElementsByClassName('image-zoom-wrapper-zoomed')[0].click() } catch(e) {} });
```

**Comment by textpain** [comment]
Yes, it's amazing. I'll definitely add it ASAP

**Comment by textpain** [comment]
I did it, you may now update to v2.2.0. Thanks for your suggestion!
