### ISSUE TITLE
doesn't work in an image gallery while using with framer motion

### ISSUE THREAD

**Issue by deadcoder0904** [mvoloskov/fast-image-zoom#10]
so i'm using it in an image gallery but it doesn't work for some reason. i can't see the zoom-in cursor & it doesn't zoom in on click either.

how do i fix this?

demo with code → https://stackblitz.com/edit/framer-motion-image-gallery-nextjs?file=pages%2Findex.tsx

**Comment by textpain** [comment]
Hello.

Unfortunately, I know nothing about Framer Motion. My library was designed to work at the lowest, general-purpose level, e.g. HTML elements and DOM.

You may try to inspect the actual DOM elements generated by Framer, their hierarchy and events. Firefox may be useful, as for every element it can display all the event handlers attached to it.

I think "motion" part of the Framer Motion have deep attachment to DOM elements, dictating everything regarding CSS transformations and DOM events. This is often the case with JS animation libraries. Maybe that kind of control overrides a certain thing in how my lib works, breaking it.

**Comment by deadcoder0904** [comment]
cool, no problem :)
