### ISSUE TITLE
scroll listener

### ISSUE THREAD

**Issue by carlos-dubon** [mvoloskov/fast-image-zoom#13]
Sometimes we wrap our main app into another container (left sidebar and content box to the right). The lib works well if the image is placed into the body, but if placed into another container the scroll listener that un-zoom's the image doesn't work. A fix for this would be to pass the element that we want the lib to listen for scroll events.

This are the parts of the lib that need to be modified for this to work:

```TypeScript
  const destroy = () => {
    document.body.removeEventListener("click", handleClick);
    document
      .querySelector(".fast-image-zoom-content")
      ?.addEventListener("scroll", handleUnzoomingInteraction);
    //window.removeEventListener("scroll", handleUnzoomingInteraction);
    window.removeEventListener("resize", handleUnzoomingInteraction);
    document.removeEventListener("keydown", handleKeydown);
    document.head.removeChild(
      document.getElementById("image-zoom-styles") as Node
    );
  };
```

```TypeScript
  const start = () => {
    injectStyles(styles);

    getImages().forEach(processImage);

    document.body.addEventListener("click", handleClick);
    document
      .querySelector(".fast-image-zoom-content")
      ?.addEventListener("scroll", handleUnzoomingInteraction);
    //window.addEventListener("scroll", handleUnzoomingInteraction);
    document.querySelector("fast-image-zoom-content");
    window.addEventListener("resize", handleUnzoomingInteraction);
    document.addEventListener("keydown", handleKeydown);

    cb();
  };
```

**Comment by textpain** [comment]
Hi, thank you for using my library, and thank you for your suggestions.

I added the `containerSelector` attribute that isolates the plugin within an arbitrary container. Please refer to README in the latest version.

Note the CDN link change. I sincerely apologize for this, but I used a non-versioning JSDelivr link that might introduce unwanted breaking changes. This mistake is now fixed, and the new unpkg link includes a version. Just updating the script's `src` should be enough.

If you find any bugs in this new version, feel free to give feedback here.

**Comment by carlos-dubon** [comment]
Thanks for the quick response! This has solved my issue. Thanks!
