### ISSUE TITLE
Bottom padding

### ISSUE THREAD

**Issue by Nickonimus** [mvoloskov/fast-image-zoom#15]
Hi, great thing, exactly what i needed, thank you!

I want to make asymmetrical zoom, but i can't set custom bottom-padding. 
Is there a way to do this with css?

**Comment by textpain** [comment]
Hi @Nickonimus, thank you for your feedback!

To be honest, I'm not sure. Wrapping images with divs with bottom padding and changing the selector to target those divs should work. If you want a cleaner solution, you can try setting paddings for images themselves. Note that their inline styles will be destroyed as stated in README, so opting for a class name is a good solution.

Let me know how it goes!

**Comment by textpain** [comment]
Closing this for now. Feel free to reopen!
