### ISSUE TITLE
Overlapping images

### ISSUE THREAD

**Issue by Nickonimus** [mvoloskov/fast-image-zoom#17]
Hi again!
I have infinite grid canvas with images which wrapped in containers with transformation. 
Zoom works fine, but in zoomed state image overlapping with grid: 
![Screenshot 2023-05-30 135905](https://github.com/mvoloskov/fast-image-zoom/assets/118725251/dc32fde0-7afe-4323-9ba5-d6920538cb43)
![Screenshot 2023-05-30 135521](https://github.com/mvoloskov/fast-image-zoom/assets/118725251/396fc7d4-1127-4ad3-8739-dc1d0b254922)

I tried to change z-index and other settings of wrapper and .image-zoom-zoomed class but seems problem is more sophisticated.
So, maybe you have some ideas how to fix this, or where to look at the problem?

As base for the canvas i used this code: https://codepen.io/radixzz/pen/eRJKXy

**Comment by textpain** [comment]
Hi there 👋 
Can you provide a demo link?

**Comment by Nickonimus** [comment]
Uploaded as it is, not sure you'll understand all this mess :)
link for test: empwr.pp.ua

**Comment by Nickonimus** [comment]
I think problem in stacking context because of this Infinite Grid code, i checked with different zooming scripts, and everything the same.  
So guess it is better to use code i able to deal, with my modest webdev knowledges. 
Updated test link with new gallery, and everything works just great. 

So thank you for your script!

**Comment by textpain** [comment]
Sorry, didn't have enough time to check your demo 😅
Glad you liked it!
By the way, nice website!
