### ISSUE TITLE
Image max size

### ISSUE THREAD

**Issue by bdauton** [mvoloskov/fast-image-zoom#2]
Hi 👋,

I'd like to know if there's an option to limit the zoom of the image to 100% of its real size. When using huge resolution, images are excessively zoomed.

Thanks for the work 👍

**Comment by textpain** [comment]
Hi there!

There is no such option yet, but I’ll implement it ASAP. Thanks!

**Comment by textpain** [comment]
I did it. Please refer to an updated README for instructions (it basically works out of the box now).

**Comment by bdauton** [comment]
Thanks a lot!
