### ISSUE TITLE
WordPress tutorial

### ISSUE THREAD

**Issue by paaljoachim** [mvoloskov/fast-image-zoom#3]
Hey

I am looking into modifying my WordPress tutorial:
https://www.easywebdesigntutorials.com/adding-a-lightbox-to-wordpress-without-using-a-plugin/

Check out the colorbox lightbox setup method I used. Of the various lightboxes I shared there colorbox works straight out of the box so to speak.

I am curious if you are interested in helping me get fast-image-zoom working in a similar way as colorbox? If I get it to work then I can also add fast-image-zoom to the modified version of the tutorial. If you are interested in helping out then I will need step by step advice on getting it to work.

Thanks!

**Comment by textpain** [comment]
Hello! Yes, I'm always interested in making what I do more accessible.

Though I don't quite get what does it means to get it to work "out of the box". Fast-image-zoom already doesn't require any additional setup. You just add it to your page and call the initialization method, and it will take care of all the images with `alt`. 

Maybe I don't get it. Please clarify

**Comment by paaljoachim** [comment]
Hi

A tutorial would like something like this:

Fast image zoom master
https://github.com/mvoloskov/fast-image-zoom

Download the zip and extract. In the dist folder, copy fast-image-zoom.js to a new folder.
I called the new folder fast-image. 

Create a new fast-image-zoom-init.js file with the following code, and add the file to the fast-image folder.
Add the following code:

```
imageZoom({
    selector: `img[alt]:not([alt=""]):not([data-image-zoom-disabled])`,
    cb: () => {},
    exceed: false,
    padding: 20,
})
```

I assume the above code might need some adjustments when located in an init.js file.



Add the fast-image folder containing fast-image-zoom.js and fast-image-zoom-init.js into the root of the child theme. 

Add the following code to your functions.php file or a code plugin.
```
/* Enqueue Fast Image Zoom */
add_action( 'wp_enqueue_scripts', 'enqueue_fast-image’ );
function enqueue_fast-image() {
 wp_enqueue_script( 'fast-image',get_template_directory_uri() . '/fast-image/fast-image-zoom.js', array( '' ), '', true );
 wp_enqueue_script( 'fast-image-init', get_template_directory_uri() . '/fast-image/fast-image-zoom-init.js', array( 'fast-image-zoom' ), '', true ); 
}
```

This is very similar method I use for other lightbox tutorials. (I have not yet tested it out as I assume the init js file still needs some adjustments.)

**Comment by textpain** [comment]
You can just do this:
```
imageZoom()
```

This lib needs no adjustments. As soon as it's called, it processes images on the page and injects code to the head. If the page is not loaded yet, it waits.

If you're using client-side routing as in react-router, you need to initialize like this:
```
let destroy = imageZoom()
```
And also this should be called on every route change:
```
destroy()
destroy = imageZoom()
```

If your webpage reloads when a user clicks a link, you know, the traditional way of doing things on the web, you need no additional adjustments. Just call `imageZoom()` inside a script in the body, and it will do the rest.

I think WordPress doesn't have client-side routing without plugins, as it's not a JamStack framework.

**Comment by paaljoachim** [comment]
I apologize but my understanding of JavaScript is not that great.
I base the various tutorials back on Colorbox which does work nicely. Most of the other lightbox tutorials do still not.
Which means I assume there is likely an easy way to get this working when one has more knowledge of JS than I at current have. I do look for help to get this in, and will need some more basic do so and then so (hand holding) and so to get it working. Thanks!

**Comment by textpain** [comment]
make a wordpress theme. into your main template that is used for every page, insert this:
```
<script src="https://cdn.jsdelivr.net/gh/mvoloskov/fast-image-zoom/dist/fast-image-zoom.min.js"></script>
<script>
  imageZoom()
</script>
```

it should work the first try. If this code end up on the actual page, it will work.

**Comment by paaljoachim** [comment]
This is what I did:
I added a fast-image-zoom-init.js
containing this code

```
<script src="https://cdn.jsdelivr.net/gh/mvoloskov/fast-image-zoom/dist/fast-image-zoom.min.js"></script>
<script>
  imageZoom()
</script>
```

Saved it into the folder fast-image. Added the folder to the root of the active theme.

Added a custom functions file:

```
<?php

/* Enqueue Fast Image Zoom */
add_action( 'wp_enqueue_scripts', 'enqueue_fastimage' );
function enqueue_fastimage() {
 wp_enqueue_script( 'fastimage-init', get_template_directory_uri() . '/fast-image/fast-image-zoom-init.js', array( 'fast-image-zoom' ), '', true ); 
}
```

Went to a page (using WordPress Gutenberg). Linked an image to the media file. Previewed the page. Clicked the image which just opened as it usually does without any lightbox. If you notice anything off let me know. At the moment I feel like giving it a rest. As I am not seeing any obvious errors I am making.

**Comment by textpain** [comment]
I'm not familiar with wordpress, but here's the troubleshooting steps:
1. make sure the snippet I sent you is present on the actual page
2. if an image opens like that, it's wrapped with a link. make sure images are not wrapped with links. without fast-image-zoom, nothing should happen whatsoever when you click on an image.
3. make sure your images are `<img />` tags and not some divs with `background-image`.

**Comment by textpain** [comment]
I'm closing this for now. Feel free to still comment if you need further help.
