### ISSUE TITLE
Module parse failed: Unexpected token (51:54)

### ISSUE THREAD

**Issue by madebysix** [mvoloskov/fast-image-zoom#5]
Hi there,

I'm running into an issue when trying to use your image zoom plugin. If I try and use the import method that is illustrated in your Basic usage example I get the following error:

```
ERROR in ./node_modules/fast-image-zoom/src/lib.js 51:54
Module parse failed: Unexpected token (51:54)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   const vw = Math.max(document.documentElement.clientWidth || 0, window.innerWidth || 0);
|   const vh = Math.max(document.documentElement.clientHeight || 0, window.innerHeight || 0);
>   const shouldExceed = config.exceed || image.dataset?.imageZoomExceed === 'true';
|   let scale = getScale(imageHeight, imageWidth, vh, vw);
| 
 @ ./node_modules/fast-image-zoom/src/index.js 2:0-85 18:22-30 22:6-17 29:8-20 32:6-15 39:4-15 48:6-17 62:4-16 63:24-36
 @ ./src/js/c-ImageAndZoom.js
 @ ./src/js/modules.js
 @ ./src/index.js
 @ multi ./src/sass/main.scss ./src/index.js
```

However if I use your cdn example I don't get the error, which I'm assuming is because the cdn is using a minfied file.

Im just wondering if you have come across this issue before and know of a solution as I would prefer to use the import approach in my project if possible.

Cheers
Jack

**Comment by textpain** [comment]
Hello.

It seems like your build system doesn't use the latest ES standard. The error is clearly with the `?` — the [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining). You should find a way for your build system to support it. The common way is setting up Babel, so it works with the latest JavaScript standard.

Alternatively, you can always use CDN. Minified or non-minified, the CDN file is compiled to work as plain old IIFE. However, ES modules approach uses the latest ES syntax and its features such as optional chaining.

**Comment by madebysix** [comment]
Hi,

Cheers for pointing me in the right direction, I was already running babel on the current project but it didn't seem to allow for the optional chaining, managed to get it to work now by using: https://babeljs.io/docs/en/babel-plugin-proposal-optional-chaining

Thanks again for the help.

Cheers,
Jack

**Comment by textpain** [comment]
Glad to help!
