### ISSUE TITLE
Thoughts when using Framer Motion?

### ISSUE THREAD

**Issue by deadcoder0904** [mvoloskov/fast-image-zoom#6]
Hey @mvoloskov so I'm using `fast-image-zoom` & love it but the zoom-in & zoom-out cursors are blurry. Mostly because they are not SVG but rather cursors. They are also blurry on Medium.

I had a thought. What if I use Framer Motion to zoom-in & zoom-out images rather than using this library? Any pros & cons as you've probably spent more time than me thinking about this problem?

**Comment by textpain** [comment]
Hey! Glad to know that you liked it.

Cursors are not just images — they are a crucial part of accessibility. From browser to browser, from OS to OS, cursors look different, and it's necessary to preserve that to avoid confusion. Also, native cursors can potentially be recognized by accessibility tools while SVG images can't.

I used all sorts of operating systems: different Linux distros, Windows from 95 all the way up to Windows 10, macOS from High Sierra to Big Sur. I never had any problems with blurry cursors — they were always crisp. May it be the problem in your OS setup?

If you want, you can always fork my library and modify it as it uses BSL-1.0 as its license. Among other things, you can customize cursors as you wish. Though, I suggest you also considering accessibility concerns of doing so.

**Comment by textpain** [comment]
Also, my library uses just one event listener to handle all images and another event listener that listens to scroll to zoom out when needed. As for zooming, I use just one precisely calculated CSS transform.

As of today, I don't see how this could be done more efficiently with CSS in terms of performance overhead and bundle size. The only way to improve it really is using WebGL to handle zooming. You will surely win on performance but lose vastly on bundle size as it will inevitably be much larger. If you already use WebGL, it may be a good idea to avoid CSS transitions altogether and rely on WebGL instead. But if you don't, I really don't see the point in using WebGL only to zoom images. In this case, a CSS solution like mine will be better.

**Comment by deadcoder0904** [comment]
> Cursors are not just images — they are a crucial part of accessibility. From browser to browser, from OS to OS, cursors look different, and it's necessary to preserve that to avoid any confusion. Also, native cursors can potentially be recognized by accessibility tools while SVG images can't.

I'm not an expert but you can absolutely set a `title` on an SVG. I also put `aria-label` on a `button` that wraps the SVG but like I said, definitely not an a11y expert.

> May it be the problem in your OS setup?

Nope, OS has nothing to do with it. I'm on a Macbook Pro 2016 Retina. If anything, it's a Browser problem but it shouldn't be as I use Chrome.

> Also, my library uses just one event listener to handle all images and another event listener that listens to scroll to zoom out when needed. As for zooming, I use just one precisely calculated CSS transform.

This is great. I'll try replicating in Framer Motion. The reason I want to replicate is animations in Framer Motion look really amazing as it uses physics rather than CSS transforms. And for some reason, there is a waiting time when I click on the image for the first time so it loads after 1-2 seconds which feels too slow. Thank you for your input :)

**Comment by textpain** [comment]
You can't set a `title` attribute on SVG. You can totally specify `<title>` inside SVG, but that won't work if you use that SVG as background image.

Even if you can achieve labelling with something like
```
.cursor::after {
    content: 'Zoom';
    display: inline;
    background-image: url(...);
    font-size: 0;
}
```

...that label is still unreachable as it will be impossible to focus on that element. With screenreader it's reachable though, but just imagine the inconvenience of moving the focus up and down to catch the mouse cursor.

The good enough solution will be to make a transparent button on top of an image that will say "Zoom image", but that's cumbersome.

Again, cursors are special and cannot be replicated with HTML, CSS and JS.

Also, remember that when you use WebGL tools, you completely lose accessibility as it'll be just `<canvas>` with some pixels that is absolutely unreadable with screenreaders as-is. You'll have to make an announcement mechanism for your users to be able to get what's going on there. Also, you will completely lose SSR (bye-bye simple SEO), Lighthouse score and browser accessibility tools such as WCAG 2.0 color checker as they will be unable to "parse" your canvas pixel content and figure out your UI elements.

You'll basically have to implement everything from scratch.

**Comment by deadcoder0904** [comment]
Damn, that sounds painful. I'll keep using this then 😂

**Comment by textpain** [comment]
I don't know how Framer operates. As it's a cross-platform solution that can be compiled to mobile apps among other things, you have to try accessibility yourself, with screenreaders on every platform you release on. Maybe Framer have some accessibility support built in.

What I just described is relevant only if you use WebGL explicitly, like with ThreeJS, Unity or anything that has something to do with WASM.
